//! A simple IR like rust's MIR, to make codegen backend creation easier

#[derive(Debug,Clone)]
pub enum Value {
    Unreachable,
    ImplicitUnit,
    Local(LocalIndex, WrapperList),
    Named(crate::ast::path::AbsolutePath, WrapperList),
    Deref { ptr: LocalIndex, wrappers: WrapperList },
    StringLiteral(crate::ast::StringLiteral),
    IntegerLiteral(u128, ),
}
impl Value {
    fn field(&self, idx: usize) -> Value {
        match self {
        Value::Unreachable => Value::Unreachable,
        Value::ImplicitUnit => panic!("Field on void"),
        Value::StringLiteral(..) => panic!("Field on string"),
        Value::IntegerLiteral(..) => panic!("Field on integer"),
        Value::Local(root, wrappers) => Value::Local(*root, wrappers.with_added(Wrapper::Field(idx))),
        Value::Named(root, wrappers) => Value::Named(root.clone(), wrappers.with_added(Wrapper::Field(idx))),
        Value::Deref { ptr, wrappers } => Value::Deref { ptr: *ptr , wrappers: wrappers.with_added(Wrapper::Field(idx)) }
        }
    }
}

/// List of access wrappers to a value (indexing and field accesses)
/// 
/// Dereferencing is handled with different value types
#[derive(Default,Clone)]
pub(super) struct WrapperList(Vec<u32>);
impl WrapperList {
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
    pub fn with_added(&self, w: Wrapper) -> Self {
        WrapperList(self.0.iter().copied()
            .chain(::std::iter::once(Self::encode(w)))
            .collect())
    }
    pub fn add(mut self, w: Wrapper) -> Self {
        self.push(w);
        self
    }
    pub fn push(&mut self, w: Wrapper) {
        self.0.push(Self::encode(w));
    }

    fn encode(w: Wrapper) -> u32 {
        match w {
        Wrapper::Field(idx) => idx as u32,
        Wrapper::IndexBySlot(LocalIndex(s)) => (1 << 31) | s as u32,
        }
    }

    fn decode(v: u32) -> Wrapper {
        if v & 1 << 31 == 0 {
            Wrapper::Field(v as usize)
        }
        else {
            Wrapper::IndexBySlot(LocalIndex( (v & 0x7FFF_FFFF) as usize ))
        }
    }
}
impl ::core::fmt::Debug for WrapperList {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("[")?;
        for v in &self.0 {
            write!(f, "{:?},", Self::decode(*v))?;
        }
        f.write_str("]")?;
        Ok( () )
    }
}
#[derive(Debug)]
pub(super) enum Wrapper {
    Field(usize),
    IndexBySlot(LocalIndex),
}
/// Non-branching operations (aka statements)
#[derive(Debug)]
pub enum Operation {
    /// Assign a value to a local variable
    AssignLocal(LocalIndex, WrapperList, Value),
    /// Assign a value to a global variable
    AssignNamed(crate::ast::path::AbsolutePath, Value),
    /// Create an instance of a composite value (tuple or struct)
    CreateComposite(LocalIndex, Option<crate::ast::path::AbsolutePath>, Vec<Value>),
    //// Cast a value to a differen type (primitives only)
    //Cast(LocalIndex, Value),
    /// Binary operation
    BinOp(LocalIndex, Value, BinOp, Value),
    /// Unary operation
    UniOp(LocalIndex, UniOp, Value),
    /// Bitwise shift, different operation because it doesn't require equal types
    BitShift(LocalIndex, Value, BitShift, Value),
    /// Take a borrow/pointer to a local variable, with a flag indicating if it's a mutable borrow
    BorrowLocal(LocalIndex, bool, LocalIndex, WrapperList),
    /// Take a borrow/pointer based on an existing pointer
    PointerOffset(LocalIndex, bool, LocalIndex, WrapperList),
}
#[derive(Debug)]
pub enum BinOp {
    Add, Sub,
    Mul, Div, Rem,

    BitOr, BitAnd, BitXor,
}
#[derive(Debug)]
pub enum BitShift {
    Left,
    Right,
}
#[derive(Debug)]
pub enum UniOp {
    Not, Neg,
}
#[derive(Debug)]
pub enum Terminator {
    /// Jump immediately to another block
    Goto(BlockIndex),
    /// Return from the current function
    Return(Value),
    /// Compare two values and jump based on the result
    Compare(Value, CmpOp, Value, BlockIndex, BlockIndex),
    /// Call a function
    CallPath(LocalIndex, BlockIndex, crate::ast::path::AbsolutePath, Vec<Value>,),
    /// Runtime assertion - unreachable code (generated by `match`)
    Unreachable,
}
#[derive(Debug)]
pub enum CmpOp {
    Eq,Ne,
    Lt,Le,
    Gt,Ge,
}

#[derive(Clone, Copy)]
#[derive(Debug)]
pub struct BlockIndex(pub usize);
#[derive(Clone, Copy)]
#[derive(Debug)]
pub struct LocalIndex(pub usize);

#[derive(Debug)]
pub struct Block
{
    //pub args:
    pub statements: Vec<Operation>,
    pub terminator: Terminator,
}
#[derive(Debug)]
pub struct Expr
{
    pub locals: Vec<crate::ast::Type>,
    pub blocks: Vec<Block>,
}

pub fn from_expr(parent: &mut super::State, expr_root: &crate::ast::ExprRoot) -> Expr
{
    let mut expr_visit = from_expr::Visitor::new(parent, &expr_root.variables);
    let ret_val = expr_visit.visit_expr(&expr_root.e);
    expr_visit.finish(ret_val)
}
mod from_expr;